### ISSUE TITLE
Add Sitemap functionality

### ISSUE THREAD

**Issue by EliCarenza** [EliCarenza/Eleventy-DaisyUI-Template#2]
Sitemaps are important for SEO. Let's add the plugin and have them be developed dynamically.

**Comment by alexandroschanas** [comment]
Hello @EliCarenza  , if the project enviroment is in wordpress i can help with this implementation.

**Comment by EliCarenza** [comment]
Resolved in commit 71e99d9b1d6fe043939ffef6642ce3e01dfbc9e6
